name: shareweel_app

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  image_picker: ^1.1.2
  http: ^1.2.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  google_sign_in: ^6.2.2
  firebase_auth: ^5.4.2
  geolocator: ^13.0.2
  shared_preferences: ^2.5.1
  cloud_firestore: ^5.6.3
  geocoding: ^3.0.0
  dependencies:
  
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  firebase_storage: ^12.4.2
  flutter_polyline_points: ^2.0.0
  location: ^5.0.0
  provider: ^6.1.0
  dio: ^5.4.0
  flutter_google_maps_webservices: ^1.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#673AB7"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/me.jpg
