version: "3.8"

services:
  fastapi-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    env_file:
      - .env
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8080
